version: "2"

services:
  sonarqube:
    container_name: sonar
    image: library/sonarqube:8.6.1-community
    depends_on:
      - db
    ports:
      - "9001:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar/sonarqube_data:/opt/sonarqube/data
      - ./sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube_logs:/opt/sonarqube/logs
      - ./sonar/sonarqube_temp:/opt/sonarqube/temp
  db:
    container_name: sonar-postgres
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./sonar-postgres/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./sonar-postgres/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
